language: bash

git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules 
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - sudo apt-get update && sudo apt-get install -y make libarchive-zip-perl git gcc-multilib vim

install:
    - uname -a
    - pwd
    - git clone https://github.com/spark/firmware.git firmware
    - cd firmware
    - git checkout release/stable
    - cd ..
    - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2
    - tar xjf gcc-arm*.tar.bz2
    - export PATH=$PATH:/home/travis/build/cpipilas/vehicle-testing/gcc-arm-none-eabi-4_9-2015q3/bin
    - arm-none-eabi-gcc --version
    - mkdir particleGeoLoc
    - cp -Rf vehicle-testing lib particleGeoLoc
    - cd firmware/main
    - make all PLATFORM=photon APPDIR=../../particleGeoLoc
    - cd ../../

script:
    - echo "script phase"

after_success:
    - echo "after_success phase"

after_script:
    - echo "after_script phase"